on: push
name: post package
jobs:
  package-post:
    name: post
    runs-on: ubuntu-latest
    steps:

    - name: Get latest codes
      uses: actions/checkout@v2
      
    - name: version update
      run: version patch
        
    - name: NPM Publish
      uses: JS-DevTools/npm-publish@v1
      
      with: 
        token: ${{ secrets.NPM_AUTH_TOKEN }}
