name: Publish Package to npm
on: push
 
jobs:
 package-post:
  name: post
  runs-on: ubuntu-latest
  steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
